# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46c5b9f1797bde449232a93645dabd968a31c5dce1c05aac04e8e880313dcf31e4d122eb42553d874691e159aa17dd97623ffbe19690a7ee339aee69b3aeec58

test:
  secret_key_base: 033c6652697d03c3c9dfbb47f43fbab4680f66a89a48ebc15d1f4548eb4c42bd88f5710f325d18f33139641e6e76e99ad825abac0fd4d0ac41b306bdeb3d1589

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
